spring.application.name=Backend

server.port=8080

# ==========================================================
# PostgreSQL
# ==========================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/minutesmind
spring.datasource.username=postgres
spring.datasource.password=Akhil@04
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================================
# Hibernate / JPA
# ==========================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ==========================================================
# Multipart Upload
# ==========================================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# ==========================================================
# JWT
# ==========================================================
jwt.secret=VGhpc0lzQVN1cGVyTG9uZ0Jhc2U2NEVuY29kZWRTZWNyZXRLZXlGb3JNZWV0TWluZEFJQXBwbGljYXRpb25IUzM4NA==
jwt.access-expiration=3600000
jwt.refresh-expiration=2592000000

# ==========================================================
# OpenAI
# ==========================================================


# ==========================================================
# Gmail SMTP
# ==========================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mdtabishfiroz31@gmail.com
spring.mail.password=hgvhdrnztkmunymq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ==========================================================
# Swagger
# ==========================================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ==========================================================
# Logging
# ==========================================================
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE